### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by donald-ning** [ReekyStive/CourseTable2ICS#1]
<img width="725" alt="截屏2021-07-29 上午8 07 38" src="https://user-images.githubusercontent.com/54016368/127411904-2698a889-002c-4823-8ce8-6469b9a94e96.png">

**Comment by lennondotw** [comment]
需要安装 `lxml`，忘了写进 `requirements.txt` 里，已更新

``` bash
$ pip install lxml
```

**Comment by lennondotw** [comment]
Update: 现在已经不需要 `beautifulsoup4` 和 `lxml` 了
